language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - composer self-update
  - composer install

script:
  - phpcs --standard=vendor/magento-ecg/coding-standard/Ecg --ignore=vendor .
